[package]
name = "adventurers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
adventurers_quest = { path = "../adventurers_quest" }
serde_json = "1.0.95"
serde_with = "2.3.1"
termgame = "^1.2.0"
